"""
Django settings for onlineshop project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(os.path.dirname(
#     os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'jb8b&gsiugyhk0r$@fh8yu2+7774upynqmfolep@*ztcbmqr3a'
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'crispy_forms',
    'django_countries',
    'stripe',

    'home',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'onlineshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'Templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'home.apptemplates.load_setting'
            ],
            # 'libraries':{
            #     'cart_template_tags': 'home.templatetags.cart_template_tags',
            #
            # }
        },
    },
]

WSGI_APPLICATION = 'onlineshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# emails
# DEFAULT_FROM_EMAIL = 'prabhakaranbala8@gmail.com'
# SERVER_EMAIL = 'prabhakaranbala8@gmail.com'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_USE_TLS = True
# EMAIL_HOST = 'mail.********.com'
# EMAIL_HOST_USER = 'prabhakaranbala8@gmail.com'
# EMAIL_HOST_PASSWORD = '*******'
# EMAIL_PORT = 587

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# VENV_PATH = os.path.join(BASE_DIR)
# STATIC_ROOT = os.path.join(VENV_PATH, 'static_root')
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(VENV_PATH, 'media')

# VENV_PATH = os.path.join(BASE_DIR)
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_root')

# Stripe settings

if DEBUG:
    STRIPE_TEST_PUBLIC_KEY='pk_test_51HT8HGLDTNwpDpBQ59l0dDtge2bUJijJoxFGeAbIV2t7iWFYsndB3CEZ7jmSYYAKEnWe7Ej5ZPsiqWw71s4tM1LB00CiImzDj2'
    STRIPE_TEST_SECRET_KEY='sk_test_51HT8HGLDTNwpDpBQ2hJXL7wUpsxeVmMOanGkjTjcOtYxTOwnQsDPLNel93NQ0WWlUxdxEwivcGxwwXHryNnw8t9L00moxI8o7U'
else:
    STRIPE_PUBLIC_KEY = 'pk_test_51HT8HGLDTNwpDpBQ59l0dDtge2bUJijJoxFGeAbIV2t7iWFYsndB3CEZ7jmSYYAKEnWe7Ej5ZPsiqWw71s4tM1LB00CiImzDj2'
    STRIPE_SECRET_KEY = 'sk_test_51HT8HGLDTNwpDpBQ2hJXL7wUpsxeVmMOanGkjTjcOtYxTOwnQsDPLNel93NQ0WWlUxdxEwivcGxwwXHryNnw8t9L00moxI8o7U'

# Django allauth settings

AUTHENDICATION_BACKENDS = {
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
}
SITE_ID = 1

LOGIN_REDIRECT_URL = '/'

# CRISPY FORMS
CRISPY_TEMPLATE_PACK = 'bootstrap4'
